platform :ios, '11.2'

target 'AuthenticJob' do
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire-SwiftyJSON'
  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0' 
  pod 'SDWebImage', '~> 4.0'
end
